# Generated by Django 3.0 on 2020-10-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corona',
            name='datetime',
        ),
    ]
